include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - example/build/**
    - .dart_tool/**
    - spikes/**

linter:
  rules:
    public_member_api_docs: true
